name: Update
on:
   schedule:
    - cron: 0 0 * * 6

jobs:
  package-update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set remote url
      run: git remote set-url --push origin https://Ninad99:${{ secrets.UPDATE_DEPS }}@github.com/angular-graphql

    - name: GitHub Action for package.json update.
      uses: taichi/actions-package-update@v0.5.0
      env:
        AUTHOR_EMAIL: ninuch7@gmail.com
        AUTHOR_NAME: Ninad Subba
        EXECUTE: "true"
        GITHUB_TOKEN: ${{ secrets.UPDATE_DEPS }}
        LOG_LEVEL: debug
      with:
        args: -u --packageFile package.json --loglevel verbose
